### ISSUE TITLE
Version number in composer manifest of package "themes" is missing or invalid

### ISSUE THREAD

**Issue by lisandi** [typo3-themes/themes#107]
We updated today extensions from TER and than this message poped up and the extension manager is no more accessible
check also here: http://wiki.typo3.org/index.php/ExceptionCMS/1395614959
similar problem!

**Comment by kaystrobach** [comment]
This is a bug in extension manager, simply remove the composer.json ...

----- Originale Nachricht -----
Von: Andreas Becker <notifications@github.com>
Gesendet: 11.09.2015 - 01:58
An: typo3-themes/themes <themes@noreply.github.com>
Betreff: [themes] Version number in composer manifest of package "themes" is missing or invalid (#107)

**Comment by lisandi** [comment]
ok thanks kay


With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,



*ANDI BECKER*

CEO/General Manager LisAndi Co., Ltd.

*--------------------------------------------------*
*LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com


--------------------------------------------------
This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by kaystrobach** [comment]
The latest typo3 CMS 6.2 Version should also be able to handle it directly

----- Originale Nachricht -----
Von: Andreas Becker <notifications@github.com>
Gesendet: 12.09.2015 - 01:05
An: typo3-themes/themes <themes@noreply.github.com>
Betreff: Re: [themes] Version number in composer manifest of package "themes" is missing or invalid (#107)

**Comment by kaystrobach** [comment]
should work with latest TYPO3 6 LTS if not, please reopen

**Comment by lisandi** [comment]
Hi Kay it is still existing that error in 6.2.15 LTS

when updating extensions from git it disappears but therfore we are getting
now

Property
TYPO3\CMS\Extensionmanager\Service\ExtensionManagementService::$listUtility
does not exist

https://forge.typo3.org/issues/69619
https://forge.typo3.org/issues/55877 (works to solve that problem, - clear
all cache)


With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,



*ANDI BECKER*

CEO/General Manager LisAndi Co., Ltd.

*--------------------------------------------------*
*LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com


--------------------------------------------------
This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by kaystrobach** [comment]
also erledigt?
