### ISSUE TITLE
Add page properties in default fluid variables

### ISSUE THREAD

**Issue by Gloumi** [typo3-themes/themes#108]
It would be great if we can access to any page properties in fluid template. I think the use of f:cObject and typoscript library isn't the best solution to access to these properties. Fluid variables are here for that :) 

See discussion here for more information : https://typo3.slack.com/archives/typo3-themes/p1442049226000062

**Comment by kaystrobach** [comment]
Is access to the TSFE thingy enough or do you need the whole page domain model?

----- Originale Nachricht -----
Von: Gloumi <notifications@github.com>
Gesendet: 13.09.2015 - 18:04
An: typo3-themes/themes <themes@noreply.github.com>
Betreff: [themes] Add page properties in default fluid variables (#108)

**Comment by kaystrobach** [comment]
@Gloumi like in the mentioned commit? if this is enough and you give positive feedback i can include that in the repo pretty easy ;)

**Comment by Gloumi** [comment]
Accepted with bad account sorry :)
Thanks for the feature !
