### ISSUE TITLE
Constants category theme should be renamed to site or portal

### ISSUE THREAD

**Issue by typo3gov** [typo3-themes/themes#110]
the category theme in the themes BE module should be renamed to site or portal as it contains site-specefic settings and not theme-specific settings

Example: you could use a theme for different sites in a multi-site pagetree.

<img width="614" alt="themes_cat" src="https://cloud.githubusercontent.com/assets/9655337/9980149/cef68f04-5f8d-11e5-8951-d881cf24edea.png">

**Comment by kaystrobach** [comment]
we can do that via `f:translate` so internally this will still be themes to avoid confusion

**Comment by kaystrobach** [comment]
fixed in current master
