### ISSUE TITLE
Categories for themes settings should be configurable via user groups

### ISSUE THREAD

**Issue by typo3gov** [typo3-themes/themes#111]
It should be possible to limit the available categories of theme settings on a per user group basis

**Comment by kaystrobach** [comment]
can you specify the usecase here, as the settings are for the complete site you either have access to everything or nothing IMHO. Thanks

**Comment by kaystrobach** [comment]
available via 'mod.tx_themes.constantCategoriesToShow' ... and you need to restrict all the non needed ones in em ...
