### ISSUE TITLE
ArrayIndexViewHelper with objects

### ISSUE THREAD

**Issue by pduersteler** [typo3-themes/themes#113]
I just had a look at the ArrayIndexViewHelper class and I am wondering: Where does `$prop` come from? Shouldn't that be `$index` ?

```
public function render($object, $index) {

		if(is_object($object)) {
			return $object->$prop;
		}
		elseif(is_array($object)) {
			if(array_key_exists($index, $object)) {
				return $object[$index];
			}
		}
		return NULL;
	}
```

**Comment by kaystrobach** [comment]
you are right, this is a refactoring left over, i will add $prop again

**Comment by kaystrobach** [comment]
please review the attached PR :smile: thanks a lot
