### ISSUE TITLE
when placing a CE inside a grid container CE does not show up

### ISSUE THREAD

**Issue by lisandi** [typo3-themes/themes#128]
We created a gridelement - layout - 3 Column
Than created 3 Text with media elements
Only the Header of the Gridelement gets displayed

When moving the CE's out of the Container, all show up normal.

We tried same also with layout - Container - same result

We are using in one site the TER Versions of Gridelements
and in another everything current Version of Git reporsitories from Gridelements and Themes

We tried Themes - Bootstrap, Moasic, Highland - but same problem.

**Comment by Bunnyfield** [comment]
Could you please move that to the themes_gridelements extension or even to the official Gridelements tracker, since it has nothing to do with themes?
