### ISSUE TITLE
Fluid templates contains some un-translated labels

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes#130]
For example:
themes/Resources/Private/Partials/Themes/ThemeSmallPreview.html

The labels must be used with f:translate and the translation must be inserted into the xlf files!

**Comment by kaystrobach** [comment]
:smile: we are accepting pull requests

**Comment by tdeuling** [comment]
under all incoming pull requests we'll raffle some giveaways and you'll get your own contributor entry!!

**Comment by Shade634** [comment]
https://crowdin.com/page/open-source-project-setup-request <- might be intresting too?

**Comment by kaystrobach** [comment]
Thank you, but we could also use the typo3 localization server. Objections?

Von meinem iPhone gesendet

**Comment by Shade634** [comment]
None here.

**Comment by kaystrobach** [comment]
Should be replaced with own ones anyway
