### ISSUE TITLE
Themes constant manager view basic group only

### ISSUE THREAD

**Issue by fazzyx** [typo3-themes/themes#132]
Since version 2.5.3 only the basic group view is available. There is no behavior any more after check the Advanced or Expert checkbox. See attached screenshot. This was working with version 2.5.2.
![themes constants](https://cloud.githubusercontent.com/assets/6721027/12296441/f5daec9e-ba07-11e5-8e97-3efcb97723af.png)

**Comment by JPDesign** [comment]
Have a look for your static_info_tables version. After an update to 6.3.6 the error was gone in my installation and the options are shown again.

**Comment by Bunnyfield** [comment]
Fixed in 2.5.4

**Comment by fazzyx** [comment]
I can confirm that it is working with version 2.5.4 again. Thanks!
