### ISSUE TITLE
[FEATURE] Work out a themes categorie for themes.mode

### ISSUE THREAD

**Issue by t-zimmermann** [typo3-themes/themes#135]
In some of the extensions of themes distribution you can find setupts - files with Conditions for themes.mode.
This could be useful to switch development-context according to TYPO3_Context.
Therefore it would be useful to change a constant themes.mode.isDevelopment to themes.mode and make a type: options. Also cat=theme.mode has to be added to basic.categoriesToShow

**Comment by kaystrobach** [comment]
* these constants are set depending on the TYPO3 Context.
  see https://github.com/typo3-themes/themes/blob/master/Classes/Domain/Model/AbstractTheme.php#L292 and https://github.com/typo3-themes/themes/blob/master/Classes/Utilities/ApplicationContext.php
* These constants are just booleans by demand, as this is easier to check and to read in TYPOScript this way.

So IMHO it does not make any sense to set them via the constant manager nor via the themes module ...

Feel free to reopen, if you disagree.
