### ISSUE TITLE
[HINT] Icon-Themes for the 7 branch

### ISSUE THREAD

**Issue by t-zimmermann** [typo3-themes/themes#137]
First of all, I think 7.6 is a big step ahead and I like it!
what I personally don't like, is the decision, that Icons in 7 branch are black and white or two coloured. Colour also transports information. And black & white maybe fancy at the moment, but I found myself many times in sighing as I tried to find orientation in this "black & white shit". Anyway, it's decided to do like this!
Also in my favourite desktop display manager (i'm mainly working on linux KDE), they decided to choose the same way to implement icons (what I personally refuse).

Themes is such a big and powerful project and I found you also have to create Icons sometimes....
At the moment, themes is the only big project, i'm involved a littlebit.
But , if you are thinking about, what Icon you should give to a special task, maybe this is a good starting point:
It's mostly really flat and has many parts (e.g. the Desktop-Notification-Toolbar) which are black & white. Could be useful, if new Icon-Themes would be similiar for user acceptance.
This is the actual standard-Theme for KDE Plasma 5:
https://github.com/NitruxSA/breeze-icon-theme
Please be free to share this note to main-TYPO3-Team :-)

Best regards!

Torsten

**Comment by tdeuling** [comment]
Thanks for your comments and for your contributions. So, now we have 8.7LTS and we have still monochrome icons. There are too many pros and cons - I think one of the important pro is, that the monochrome icons can be colored like you want (for example black or white).
