### ISSUE TITLE
PHP Warning: Core: Error handler (BE): PHP Warning: Declaration of KayStrobach\Themes\Domain\Model\Theme::addTypoScriptForFe(&$params, &$pObj) should be compatible

### ISSUE THREAD

**Issue by kfinke** [typo3-themes/themes#138]
I got this warning in the backend with PHP7. Everything seemed to work fine though. After switching to PHP 5.6 CGI the warning was gone.

PHP Warning
Core: Error handler (BE): PHP Warning: Declaration of KayStrobach\Themes\Domain\Model\Theme::addTypoScriptForFe(&$params, &$pObj) should be compatible with KayStrobach\Themes\Domain\Model\AbstractTheme::addTypoScriptForFe(&$params, TYPO3\CMS\Core\TypoScript\TemplateService &$pObj) in /html/typo3/typo3conf/ext/themes/Classes/Domain/Model/Theme.php line 15

PHP7
Fresh installation TYPO3 7.6.4 
themes 7.0.0
theme_bootstrap 7.0.0
themes_gridelements 7.0.0

**Comment by janhelke** [comment]
Replace

ext/themes/Classes/Domain/Model/Theme.php:117

with 

public function addTypoScriptForFe(&$params, \TYPO3\CMS\Core\TypoScript\TemplateService &$pObj) {

**Comment by tdeuling** [comment]
Thanks for the hint.

**Comment by kaystrobach** [comment]
Thank you, i will take care of releasing that one

Von meinem iPhone gesendet
