### ISSUE TITLE
The fields variants, behaviour and responsive missing from TYPO3 version 7.6.6

### ISSUE THREAD

**Issue by fazzyx** [typo3-themes/themes#139]
After update to TYPO3 version 7.6.6 the fields "tx_themes_variants", "tx_themes_behaviour" and "tx_themes_responsive"
disappear from appearance tab of content elements.
Downgrade to TYPO3 version 7.6.5 returns the fields.
Themes version 7.0.2

**Comment by tdeuling** [comment]
Maybe the fields are displayed on the last tab?
I had a similar issue, which results from a TCA loading order issue. In that case the TCA add before/after failed.

**Comment by fazzyx** [comment]
Yes, right, but not always on the last tab, it differs by type of content element on which tab they appear.

**Comment by kaystrobach** [comment]
could you please add the problematic CEs and if you installed FSC oder CSC

**Comment by fazzyx** [comment]
All CEs with installed CSC. 
They appear on all "normal" CEs at the categories tab and with CE Grid Element on the Grid Elements tab.

**Comment by fazzyx** [comment]
![themes_typo3_7 6 6 1](https://cloud.githubusercontent.com/assets/6721027/14919378/d839120e-0e28-11e6-884c-c6caaf24ce50.png)
![themes_typo3_7 6 6 2](https://cloud.githubusercontent.com/assets/6721027/14919381/da1c70b6-0e28-11e6-962c-aace8f09c87a.png)

**Comment by tdeuling** [comment]
Is this issue fixed in with TYPO3 7.6.7?
I've just updated an instance and everything's placed on it's destinated location.

**Comment by fazzyx** [comment]
Yes, with this version the fields are back on the right tab now.

**Comment by tdeuling** [comment]
Ok
