### ISSUE TITLE
addTypoScriptForFe var type error

### ISSUE THREAD

**Issue by Gloumi** [typo3-themes/themes#140]
When typo3temp folder is empty I get this error : 
`Declaration of KayStrobach\Themes\Domain\Model\Theme::addTypoScriptForFe(&$params, &$pObj) should be compatible with KayStrobach\Themes\Domain\Model\AbstractTheme::addTypoScriptForFe(&$params, TYPO3\CMS\Core\TypoScript\TemplateService &$pObj) in /var/www/audencia.local/typo3conf/ext/themes/Classes/Domain/Model/Theme.php line 15`

The problem seems comming from this line :
https://github.com/typo3-themes/themes/blob/master/Classes/Domain/Model/AbstractTheme.php#L218 

If I just remove the var type, it works, but I think that's not the real solution :

`public function addTypoScriptForFe(&$params, \TYPO3\CMS\Core\TypoScript\TemplateService &$pObj)`
=> `public function addTypoScriptForFe(&$params, &$pObj)`

**Comment by kaystrobach** [comment]
Thank you for reporting we will invedtigate that

Von meinem iPhone gesendet

**Comment by tdeuling** [comment]
This error was already fixed with issue #138 
See Git/Master - we just need a new release!

**Comment by Gloumi** [comment]
Ok great ! Thanks a lot, I will wait for the release :)

**Comment by kaystrobach** [comment]
@Gloumi is it possible, that you check the git version - feedback is highly appreciated!
