### ISSUE TITLE
Theme constants filter bug

### ISSUE THREAD

**Issue by criwe** [typo3-themes/themes#144]
When hitting "enter" in Theme constants filter a back is loaded in the backend.

TYPO3 7.6
dyncss 	0.7.9 
dyncss_less 	0.7.7 
themes 	7.0.3 
PHP 7

Best,
Chris

**Comment by kaystrobach** [comment]
Hello criwe,

In which module are you, what are you doing and what are you expecting? Maxbe you can add some screenshots.

**Comment by criwe** [comment]
Hi Kay,
sure! I´m in the "configure theme" module.  I hope the problem gets a bit clearer with theses Screenshots:

![screen_02](https://cloud.githubusercontent.com/assets/7531138/18809434/59abe73c-827b-11e6-8bbb-74be1810d4cd.jpg)
![screens_01](https://cloud.githubusercontent.com/assets/7531138/18809435/59d138ca-827b-11e6-9b7f-75f2f3c55a40.jpg)

Expecting: I think hitting enter in this inputfield should just do nothing.
Best,
Chris

**Comment by tdeuling** [comment]
Hi Chris,
thanks for your report. The issue should be fixed in current master.
