### ISSUE TITLE
[] operator not supported for strings

### ISSUE THREAD

**Issue by typo360** [typo3-themes/themes#148]
Bitnami MAMP Stack 7.10
Php 7.10
TYPO3 7.6.14

When i include the "themes" static, with css or fluid styles_content the frontend is broken with this message: 
Oops, an error occurred!
[] operator not supported for strings

**Comment by pgampe** [comment]
Do you have a stacktrace or at least the line of the error?

**Comment by tdeuling** [comment]
Which version? Last TER or git master?
Do you have other static templates included?

**Comment by tdeuling** [comment]
Is this still an issue? Are you able to give more information?
Otherwise we would close this issue.
