### ISSUE TITLE
tx_themes_buttoncontent not translatable due to missing TCA

### ISSUE THREAD

**Issue by raphaelboos** [typo3-themes/themes#151]
Translating buttons is not allowed, as the TCA is missing.
This will fix it, add this to TCA of table:

```
// fix bug in themes, table not translatable by design
$GLOBALS['TCA']['tx_themes_buttoncontent']['ctrl']['languageField'] = 'sys_language_uid';
$GLOBALS['TCA']['tx_themes_buttoncontent']['ctrl']['transOrigDiffSourceField'] = 'l18n_diffsource';
$GLOBALS['TCA']['tx_themes_buttoncontent']['ctrl']['transOrigPointerField'] = 'l18n_parent';
$GLOBALS['TCA']['tx_themes_buttoncontent']['columns']['linktitle']['l10n_cat'] = 'text';
$GLOBALS['TCA']['tx_themes_buttoncontent']['columns']['linktitle']['l10n_mode'] = 'prefixLangTitle';

```

**Comment by kaystrobach** [comment]
please review the related merge request ... thanks a lot.

**Comment by raphaelboos** [comment]
Sehr geehrte Damen und Herren,

Das Büro ist von Donnerstag den 23.08.2018 bis Sonntag den 09.09.2018 nicht besetzt. Sie erreichen mich wieder ab Montag 10.09.2018 im Büro. In dringenden Notfällen erreichen Sie mich mobil unter ++49 176 55036891. 

Bitte eine SMS hinterlassen, falls Sie mich nicht sofort erreichen können. 


Herzliche Grüße
Raphael Boos
--------------------------------------------------------
soft.works | dipl.betr.wirt (fh) raphael boos 
gängle 11 | d 88131 lindau 
tel ++49 (0)8382 2735740 | email smorp@soft-works.de 
USt.IDNr. DE 153757988
--------------------------------------------------------
Hauptgeschäftszeiten:
Mo - Fr      09:00 - 12:30
Mo, Mi, Do 14:00 - 17:30 
--------------------------------------------------------
