### ISSUE TITLE
Exception in TYPO3-Themes when switching from PHP 5.6 to PHP 7

### ISSUE THREAD

**Issue by t-zimmermann** [typo3-themes/themes#155]
when:
trying to reach any page in frontend or login to backend on an Ubuntu14.04-machine
saying:
#1: PHP Warning: Declaration of KayStrobach\Themes\Domain\Model\Theme::addTypoScriptForFe(&$params, &$pObj) should be compatible with KayStrobach\Themes\Domain\Model\AbstractTheme::addTypoScriptForFe(&$params, TYPO3\CMS\Core\TypoScript\TemplateService &$pObj) in /path/to/my/typo3/typo3conf/ext/themes/Classes/Domain/Model/Theme.php line 15

To reproduce:
working TYPO3 instance 7.6.16 with the themes-extensions as follows:
themes: 7.0.2
themes_gridelements: 7.0.1
gridelements: 7.1.0

working: PHP Version 5.6.30-7+deb.sury.org~trusty+1, Server API 	FPM/FastCGI 
Then I installed in parallel new PHP-7 packages. Before switching to it I cleared all caches.
When I switch to it 
(by just changing SetHandler php56-fcgi-www to SetHandler php70-fcgi-www in my Apache default-conf and start service php7.0-fpm), it is 
not working: PHP Version 7.0.17-2+deb.sury.org~trusty+1, Server API FPM/FastCGI 
and throws the mentioned exception.

**Comment by kaystrobach** [comment]
hi @t-zimmermann is it possible for you to add a Pull request? Basicly the extending class needs to provide the same interface

**Comment by kaystrobach** [comment]
please use 7.0.3 https://github.com/typo3-themes/themes/blob/7.0.3/Classes/Domain/Model/Theme.php#L117

**Comment by t-zimmermann** [comment]
O.K. I don't know why my last: git submodule update didn't made that but 7.0.3 works for me! Thanks
