### ISSUE TITLE
[DEPRECATED] PageRenderer->addJSCSS

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes#161]
Using file references to resolve "/var/www/typo3_src-8.7.0/typo3conf/ext/themes/Classes/Hooks/PageRenderer.php:
KayStrobach\Themes\Hooks\PageRenderer->addJSCSS" has been deprecated in TYPO3 v8 when calling GeneralUtility::callUserFunction(), 
make sure the class is available via the class loader. This functionality will be removed in TYPO3 v9.

**Comment by kaystrobach** [comment]
can you point to the replacement as well please!

**Comment by kaystrobach** [comment]
Ping
