### ISSUE TITLE
[Feature] Allow overwriting the assigned theme in ThemeController->indexAction()

### ISSUE THREAD

**Issue by saitho** [typo3-themes/themes#174]
In some cases one might want to ignore the theme selected in the backend and assign a fixed one for all pages. Right now the only way to do that is overwriting the indexAction() of the ThemeController which is quite a lot of code.

Therefore I suggest assigning the _theme_ to the template from a protected function:
```
protected function getTheme() {
  $frontendController = $this->getFrontendController();
  return $this->themeRepository->findByPageOrRootline($frontendController->id);
}

public function indexAction()
{
    // ...
$frontendController = $this->getFrontendController();
$this->view->assign('theme', $this->getTheme());
    // ...
}
```
With that you would only have to overwrite _getTheme()_. Of couse you could simply assign a TEMPLATE via TypoScript, but then you would mix two different template structures.

**Comment by kaystrobach** [comment]
I do not get the use case here. Please explain that in detail. Maybe it makes sense, but for that i need to understand the idea behind it

**Comment by saitho** [comment]
I'm currently working on an implementation of Accelerated Mobile Pages (AMP) into a TYPO3 project that uses the Ext:themes. I'm providing a AMP-optimized theme which I have to apply to all pages, regardless of which layout was assigned in the backend.

**Comment by kaystrobach** [comment]
do you use a different page type for that? how do you trigger the rendering of the AMP pages?

Maybe it makes sense to use a different pagetype, we already did that in some cases.

are you on slack - maybe it makes sense to have a short talk ...

**Comment by saitho** [comment]
Closed as we discussed on Slack... I missed the easiest solution there. ^^'
