### ISSUE TITLE
clash with naming of property and gridlayout in TCA renderField

### ISSUE THREAD

**Issue by pniederlag** [typo3-themes/themes#180]
The TCA renderField classes do run into a problem when trying to add a field on a gridelement that has the same key as some other "default" property.

for example we might have a default property with the name "container", but we are also likely to have a gridelement with the key "container". Now it get's impossible to add a property for the gridelement container as this will always clash/conflict with the property "container".

Here's a full example that'll demonstrate the problem:

```
themes.content.behaviour {
	default {
		container {
			# some select to set container behaviour on element
			none = LLL:EXT:theme_bootstrap4/Resources/Private/Language/locallang_behaviour.xlf:content.behaviour.container_label
			default = LLL:EXT:theme_bootstrap4/Resources/Private/Language/locallang_behaviour.xlf:content.behaviour.container
			fluid = LLL:EXT:theme_bootstrap4/Resources/Private/Language/locallang_behaviour.xlf:content.behaviour.container_fluid
		}
	}
	gridelements_pi1 {
               # try to add a property solely on the gridelement "container"
		container {
			parallax = Test to add a property "property" on a grideElement "container"
		}
	}
}
```

Workaround:

use variant instead of behaviour to add the desired property to the grid element, as variant does not have a property with name "container".

**Comment by kaystrobach** [comment]
hey @Bunnyfield what's your opinion? should we rename that field?

**Comment by kaystrobach** [comment]
@pniederlag would you like to contribute a PR or sponsor the fix?

**Comment by pniederlag** [comment]
@kaystrobach I tried to come up with a patch but didn't get a working solution... still puzzled about a good approach. If someone want's to tackle it, I'd chip in some time for testing/coding and/or a tiny amount for paid coding/support.

**Comment by kaystrobach** [comment]
@pniederlag still a problem?

**Comment by pniederlag** [comment]
@kaystrobach thx for asking. Workaround is working so I guess there might be other things with higher priority to consider first.

**Comment by kaystrobach** [comment]
can you provide your workaround here, so i would keep that open.

**Comment by pniederlag** [comment]
workaround is already mentionded in the orginial issue (https://github.com/typo3-themes/themes/issues/180#issue-335776766)

just use a different field for adding the field (use variant instead of behaviour).

Rethinking of this my conclusion is this is not really a bug but rather correct behaviour. So I think we can just close it.
