### ISSUE TITLE
Verify yaml parser security

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/themes#195]
![grafik](https://user-images.githubusercontent.com/1185776/45075320-0b667c80-b0e7-11e8-830a-9bc3c093bb63.png)

https://app.codacy.com/app/github_130/themes/security?bid=8678819

* [ ] verify other issues given here - https://app.codacy.com/app/github_130/themes/security?bid=8678819

**Comment by tdeuling** [comment]
I think we can get rid of the YAML parser. As far as I know the core contains an own copy of it.

**Comment by kaystrobach** [comment]
please verify that with 7.6 and 8.7 and 9.4
