### ISSUE TITLE
 Plans on updating the TER version

### ISSUE THREAD

**Issue by ferdynator** [typo3-themes/themes#202]
I just wanted to know if there are any plans on updating the TER version of this extension any time soon. We still have projects without composer on web hosts without shell access. An upload to TER would simplify upgrading for us.

Also see [t3kit/theme_t3kit#464](https://github.com/t3kit/theme_t3kit/issues/464).

**Comment by kaystrobach** [comment]
Will try to add the ter release workflow to our automation setup again soon
