### ISSUE TITLE
TYPO3 v9 compatibility

### ISSUE THREAD

**Issue by christianbltr** [typo3-themes/themes#203]
It would be great if there would be support for TYPO3 v9 for this extension.

Are there any plans on further development of themes and making it compatible with TYPO3 v9?

**Comment by edekowalski** [comment]
Same Question as Christian
It would be great if there would be support for TYPO3 v9 for this extension.
Are there any plans on further development of themes and making it compatible with TYPO3 v9?
Best Regards
E.K

**Comment by kaystrobach** [comment]
Yes working on it already - hopefully until summer, currently thinking about migrating settings to sites module.

**Comment by kaystrobach** [comment]
It’s a bunch of work
