### ISSUE TITLE
Configure Theme – little Bug in enable/edit Options for colors

### ISSUE THREAD

**Issue by alexanderfiss** [typo3-themes/themes#21]
When clicking on the power on/off Button for the first color and nothing was changed, click on the 'save' Button at the top, all other color-options are editable.
Perhaps there is a bug with the colorpicker. When power on other options for languages or meta, i can't reproduce this.
![before-saving](https://cloud.githubusercontent.com/assets/6135827/3341162/e0d6e702-f885-11e3-804e-8b0989dcda09.png)
![after-saving](https://cloud.githubusercontent.com/assets/6135827/3341163/e0d75cc8-f885-11e3-93df-b63c72755f33.png)

Browser is Chrome 35.0.1916.153 on OS X 10.9.3

**Comment by kaystrobach** [comment]
not reproduceable anymore
