### ISSUE TITLE
Language switch not working in TYPO3 10

### ISSUE THREAD

**Issue by fazzyx** [typo3-themes/themes#221]
The language uid can not get by $GLOBALS['TSFE']->sys_language_uid anymore.
Can u please change this to:
`$languageUid = GeneralUtility::makeInstance(Context::class)->getAspect('language')->getId();`
in
`Classes/ViewHelpers/Widget/Controller/LanguageMenuController.php`

Thank you

**Comment by kaystrobach** [comment]
done see master

**Comment by fazzyx** [comment]
Many thanks!

**Comment by fazzyx** [comment]
Sorry I did not mention it, but can u please import the context class.
Thanks

**Comment by kaystrobach** [comment]
Oh man ... I just copied the change and did test. You are totally right.
