### ISSUE TITLE
Constants-Editor: Save colors

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes#63]
Currently the default value for @gray is 'lighten(#000, 20%)'.
By saving the constants, without changing this field, the @gray value is being converted to a red color.

**Comment by kaystrobach** [comment]
think i can't fix this, as the cms core handles that internally ... and the converter is not done on our side ...

perhaps the default can be changed to blank?

**Comment by kaystrobach** [comment]
@tdeuling can we close it?

**Comment by t-zimmermann** [comment]
I have a similar issue:
My standard-color entries in themes-editor are like this (The default values from Benjamin Kotts bootstrap_package) :
![colors-themeseditor](https://cloud.githubusercontent.com/assets/7645477/13402234/b7916396-df0f-11e5-85bb-6fabb0de9621.png)
When I edit primary-color, save and reload Themes-Constantseditor all values are strange recalculated:
![colors-themeseditorafterediting](https://cloud.githubusercontent.com/assets/7645477/13402489/d305515e-df10-11e5-88b3-a10e7ea2d7e4.png)

**Comment by kaystrobach** [comment]
still valid? never had that
