### ISSUE TITLE
Constants-Types should support the file type

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes#67]
Constants-Types should support the file type for an easier image/font selection

File type definition:
http://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/TypoScriptTemplates/TheConstantEditor/Index.html#type

**Comment by Shade634** [comment]
Can be closed?

**Comment by kaystrobach** [comment]
I do not think so, we had a problem in the constant manager of themes with files, needto investigate that again

Von meinem iPhone gesendet
