### ISSUE TITLE
Exception in TYPO3 6.2.9 in ext_tables.php

### ISSUE THREAD

**Issue by typoworx-de** [typo3-themes/themes#72]
Installing themes in TYPO3 6.2.9 throws an exception/warning that totally blocks TYPO3 complaining about a wrong type (expecting array). I was able to fix it like this:

```PHP
#'displayCond' => 'FIELD:root:REQ:true',
'displayCond' => Array(
    'AND' => 'FIELD:root:REQ:true',
),
```
I don't know yet if this is a core bug. As far as I know there still should be back-compatibility to string-types for displayCond?!

**Comment by kaystrobach** [comment]
to get an idea how the problem was created, please post a list of all installed extensions, and switch the installtool mode to development and post a possible stack trace

btw. which version of themes do you use ... git or TER?

thank you!
