### ISSUE TITLE
Confusing behavior with "themes independent mode"

### ISSUE THREAD

**Issue by smadsen** [typo3-themes/themes#93]
I experienced the following with a fresh new install of TYPO3 6.2.12 LTS:

1) Install TYPO3
2) Install EXT:theme_foundation (with all dependencies)
3) Create site root template
4) Include static templates from extensions gridelements and css_styled_content (because that's how it's set up in the vagrant themes box – and I took that as an example)
5) Choose EXT:theme_foundation as theme for the site
6) Choose a backend layout for root page

This resulted in a populated back end layout, in which I could start to insert content. However the front end rendering was empty inside the body tag resulting in blank pages. Sometimes I would get output rendering of the site – but only if I were also logged in as administrator. Everybody else saw a blank page.

What I should have done was remove the check in the checkbox secretly titled "themes independent mode" in the Extension Manager settings for the EXT:themes extension. Removing this now gave me access to be able to include the static template from the Themes extension. I did not have this option out of the box – and it also didn't appear to me that I needed it, since this is not the set up in the vagrant themes box.

**Comment by kaystrobach** [comment]
@smadsen could you please verify, that it now works, if not i will remove the independent mode finally ...

**Comment by smadsen** [comment]
@kaystrobach – It seems to work perfectly now - thanks! :+1:  
I set basic.themesIndependent = true and now I no longer have a Static template from EXT:themes – but it still works.

But I'm still not sure what this does exactly? What are the intentions with this?

**Comment by tdeuling** [comment]
The intention was, to make it more easier to use. This function should include the static template automatically by default.
In my opinion we should kick it completely.

**Comment by kaystrobach** [comment]
if it works now lets keep it ;) it's so easy to get started with it ;)

**Comment by kaystrobach** [comment]
so lets close it for now ...
