### ISSUE TITLE
No static template to include

### ISSUE THREAD

**Issue by JPDesign** [typo3-themes/themes#95]
Include static from extensions is not possible. FE output with full head-tag (CSS, JS, META...) but empty body-tag. After setting 'themes independent mode' to TRUE the static template (themes/Configuration/TypoScript/setup.txt) is auto included but still not an available item for manual inclusion. FE output is correct.

Setup:
TYPO3 6.2.12 (Upgrade from 4.5.40, multilingual)
Themes 2.4.0 (from TER)
Operating system: Unix
PHP version: 5.3.17
PHP CGI detected: No

**Comment by kaystrobach** [comment]
thanks to @tdeuling we have 2.4.2 out in TER now, so the problem should be fixed for now!

**Comment by JPDesign** [comment]
Cool, problem fixed with 2.4.2
Thx Kay and Thomas
