### ISSUE TITLE
allow easy replacement of templates of the languagemenu viewHelper

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/themes#96]
@tdeuling should we add this to the themes `setup.txt` to allow easy exchange of the templates of the language viewHelper

```
plugin.tx_themes.view.widget {
  KayStrobach\Themes\ViewHelpers\Widget\LanguageMenuViewHelper {
    templateRootPaths {
      100 = EXT:themes/Resources/Private/Templates/ViewHelpers/Widget/LanguageMenu/
      500 = {$themes.resourcesPrivatePath}Templates/ViewHelpers/Widget/LanguageMenu/
    }
   partialRootPaths {
      100 = EXT:themes/Resources/Private/Partials/ViewHelpers/Widget/LanguageMenu/
      500 = {$themes.resourcesPrivatePath}Partials/ViewHelpers/Widget/LanguageMenu/
    }
   layoutRootPaths {
      100 = EXT:themes/Resources/Private/Layouts/ViewHelpers/Widget/LanguageMenu/
      500 = {$themes.resourcesPrivatePath}Layouts/ViewHelpers/Widget/LanguageMenu/
    } 
 }
}
```

**Comment by tdeuling** [comment]
# Required file for overwriting the languagemenu widget template
## /Configuration/TypoScript/Library/plugin.themes.setupts

<code><pre>
plugin.tx_themes {
	view {
		widget {
			KayStrobach\Themes\ViewHelpers\Widget\LanguageMenuViewHelper {
				templateRootPath = EXT:theme_bootstrap_slate/Resources/Private/Templates/
			}
		}
	}
}
config.tx_extbase {
	view {
		widget {
			KayStrobach\Themes\ViewHelpers\Widget\LanguageMenuViewHelper {
				templateRootPath = EXT:theme_bootstrap_slate/Resources/Private/Templates/
			}
		}
	}
}
</pre></code>

**Comment by kaystrobach** [comment]
Sagt mir was?
